### ISSUE TITLE
Undegrad

### ISSUE THREAD

**Issue by pepoandra** [CamiloGarciaLaRotta/CamiloGarciaLaRotta.github.io#1]
Hola.
En la main page dice undegrad en vez de undergrad. 

Nada. Eso.

Chau.

**Comment by Kartoshka** [comment]
Hello,

Your main page states that you are an "undegrad" student instead of "undergrad".

Thank you

**Comment by alexboii** [comment]
Привет!

Как может коммунизм победить, если у тебя на странички написано "undegrad" вместо "undergrad?" 

Благодарю за внимание.

**Comment by boggy-d** [comment]
Buna,

Pagina ta principala afirma ca sunteti un student "undegrad" in loc de un student "undergrad".

Multumesc

**Comment by CamiloGarciaLaRotta** [comment]
fixed and tested : 3003b4524f1db55817b5220635806ddec4ed4028   

**papa bless**
